### ISSUE TITLE
ao on macos brings itself to front multiple times on startup

### ISSUE THREAD

**Issue by Seluj78** [klaudiosinani/ao#80]
Everything is in the title.

macos 10.14 and latest of ao.

**Comment by novdddd** [comment]
This is because of Microsoft not Ao. Was like this from the past 😋

**Comment by Seluj78** [comment]
Lol makes no sense. Why would it be because of microsoft ? the app handles the bring to front not microsoft lol

**Comment by novdddd** [comment]
It is same on web version. Try it. Maybe @klaussinani can work around fix it. But dont make fun of people, u violate code of conduct https://github.com/klaussinani/ao/blob/master/code-of-conduct.md
Also mayde considerered contributting with PR

**Comment by Seluj78** [comment]
Well actually no it isn't. The website makes a lot of API callbacks but it's the app that cases `bring app to front` not the website. I am no blaming Microsoft or @klaussinani, I am just saying that it is a bug.
And I am not making fun of you, I am saying that what you said makes no sense.

I also considered sending a PR but I do not know anything about Electron and Javascript in general, it isn't my field of programming.

**Comment by Modelmat** [comment]
I get this too running KDE on Arch Linux.

**Comment by alexkillen** [comment]
This happens for me to on Ubuntu 18.04, here's the About:

Version: 6.9.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic

Note I tried using the To-Do web app and it does not bring the browser into focus multiple times, just to clear up any confusion in the above comments.

**Comment by Slater91** [comment]
Same here using KDE on KDE neon. Even if I minimise the window, it keeps on bringing itself to the front which is incredibly unnerving.
